### ISSUE TITLE
Heavy mappers can't GET users stats

### ISSUE THREAD

**Issue by DenisCarriere** [AmericanRedCross/osm-stats#29]
Was having issues getting stats from a heavy mapper.

**Username**: [rps333](https://www.openstreetmap.org/user/Rps333)

`http://osmstats.redcross.org/users/596047`

Browser Feedback

```
The osmstats.redcross.org page isn’t working

osmstats.redcross.org didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by smit1678** [comment]
@DenisCarriere Do you know when `rps333` last made an edit for MissingMaps? I took a brief look at their edits and I didn't see any #missingmaps in their changeset comments in the last month or so. The system right now only tracks changesets with `#missingmaps` and that's only been tracked since late February (older missingmaps contributors were added to a users table in order to calculate the accurate number of contributors). There is a possibility that no edits have been made to be tracked by the system in the last few months.

**Comment by DenisCarriere** [comment]
That might be the case, I know he has been contributing to MissingMaps, however not adding the hastag might be the reason his account is not showing up.

Thanks for the info!

@smit1678 Feel free to close this issue, or maybe include in the API a fallback response incase the user does not have any hashtags or changesets that reflect missing maps edits.
